CREATE TABLE CAR
(
    id SERIAL PRIMARY KEY,
    plate VARCHAR(255) NOT NULL,
    brand VARCHAR(255) NOT NULL,
    power DOUBLE PRECISION NOT NULL,
    player_nickname VARCHAR(255)
);

CREATE TABLE PLAYER
(
    id SERIAL PRIMARY KEY,
    nickname VARCHAR(255) NOT NULL,
    years_old BIGINT NOT NULL
);

DROP TABLE CAR;
DROP TABLE PLAYER;
