CREATE TABLE CAR
(
    id SERIAL PRIMARY KEY,
    plate VARCHAR(255) NOT NULL,
    brand VARCHAR(255) NOT NULL,
    power DOUBLE PRECISION NOT NULL,
    player_id BIGINT NOT NULL
);

CREATE TABLE PLAYER
(
    id SERIAL PRIMARY KEY,
    nickname VARCHAR(255) NOT NULL,
    years_old BIGINT NOT NULL
);
